name: "Input Type Environment"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to ${{ github.event.inputs.environment }}
        run: echo "Deploying to ${{ github.event.inputs.environment }}"
      - run: echo "Variable APP_NAME=${{ vars.APP_NAME }}"
      - run: echo "Secret CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}"
